linters-settings:
  govet:
    enable:
      - shadow
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - hugeParam
      - rangeValCopy

linters:
  enable:
    - copyloopvar
    - gochecknoinits
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - unconvert
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "should have a package comment, unless it's in another file for this package"
    - "exitAfterDefer:"
    - "whyNoLint: include an explanation for nolint directive"
    - "go.mongodb.org/mongo-driver/bson/primitive.E"
    - "weak cryptographic primitive"
    - "at least one file in a package should have a package comment"
    - "should have a package comment"
    - 'Deferring unsafe method "Close" on type "io.ReadCloser"'
  exclude-rules:
    - linters:
        - unparam
        - unused
        - revive
      path: _test\.go$
      text: "unused-parameter"
    - linters:
        - errcheck
      path: _test\.go$
